CREATE DATABASE PIZZAMOTO;
USE PIZZAMOTO;

CREATE TABLE ORDERS (
ORDER_ID INT NOT NULL,
ORDER_DATE DATE NOT NULL,
ORDER_TIME TIME NOT NULL
);

ALTER TABLE ORDERS 
ADD PRIMARY KEY (ORDER_id);

USE PIZZAMOTO;

CREATE TABLE ORDER_DETAILS (
    ORDER_DETAILS_ID INT NOT NULL,
    ORDER_ID INT NOT NULL,
    PIZZA_ID VARCHAR(255) NOT NULL, -- Changed TEXT to VARCHAR(255)
    QUANTITY INT NOT NULL,
    PRIMARY KEY(ORDER_DETAILS_ID) -- Fixed typo in 'ORDER_DETAILS_ID'
);
